package z.z.w.test.entity.ex;

public class MerchantUrlIpEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_url_ip.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_url_ip.MERCHANT_ACCOUNT
     *
     * @mbggenerated
     */
    private String merchantAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_url_ip.PUSH_URL
     *
     * @mbggenerated
     */
    private String pushUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_url_ip.BAND_IP
     *
     * @mbggenerated
     */
    private String bandIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_url_ip.IS_VALIDE_IP
     *
     * @mbggenerated
     */
    private Integer isValideIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_url_ip
     *
     * @mbggenerated
     */
    public MerchantUrlIpEntity(Long id, String merchantAccount, String pushUrl, String bandIp, Integer isValideIp) {
        this.id = id;
        this.merchantAccount = merchantAccount;
        this.pushUrl = pushUrl;
        this.bandIp = bandIp;
        this.isValideIp = isValideIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_url_ip
     *
     * @mbggenerated
     */
    public MerchantUrlIpEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_url_ip.ID
     *
     * @return the value of merchant_url_ip.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_url_ip.ID
     *
     * @param id the value for merchant_url_ip.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_url_ip.MERCHANT_ACCOUNT
     *
     * @return the value of merchant_url_ip.MERCHANT_ACCOUNT
     *
     * @mbggenerated
     */
    public String getMerchantAccount() {
        return merchantAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_url_ip.MERCHANT_ACCOUNT
     *
     * @param merchantAccount the value for merchant_url_ip.MERCHANT_ACCOUNT
     *
     * @mbggenerated
     */
    public void setMerchantAccount(String merchantAccount) {
        this.merchantAccount = merchantAccount == null ? null : merchantAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_url_ip.PUSH_URL
     *
     * @return the value of merchant_url_ip.PUSH_URL
     *
     * @mbggenerated
     */
    public String getPushUrl() {
        return pushUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_url_ip.PUSH_URL
     *
     * @param pushUrl the value for merchant_url_ip.PUSH_URL
     *
     * @mbggenerated
     */
    public void setPushUrl(String pushUrl) {
        this.pushUrl = pushUrl == null ? null : pushUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_url_ip.BAND_IP
     *
     * @return the value of merchant_url_ip.BAND_IP
     *
     * @mbggenerated
     */
    public String getBandIp() {
        return bandIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_url_ip.BAND_IP
     *
     * @param bandIp the value for merchant_url_ip.BAND_IP
     *
     * @mbggenerated
     */
    public void setBandIp(String bandIp) {
        this.bandIp = bandIp == null ? null : bandIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_url_ip.IS_VALIDE_IP
     *
     * @return the value of merchant_url_ip.IS_VALIDE_IP
     *
     * @mbggenerated
     */
    public Integer getIsValideIp() {
        return isValideIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_url_ip.IS_VALIDE_IP
     *
     * @param isValideIp the value for merchant_url_ip.IS_VALIDE_IP
     *
     * @mbggenerated
     */
    public void setIsValideIp(Integer isValideIp) {
        this.isValideIp = isValideIp;
    }
}